[cosmic-ray]
module-path = "binarySearchTree3.py"
timeout = 40.0
excluded-modules = []
test-command = "python -m pytest --tb=no ./DYNAMOSA-MIO-MOSA-WHOLE_SUITE"

[cosmic-ray.distributor]
name = "local"
